POST {{baseUrl}}/chat
Content-Type: application/json
X-API-KEY: {{apiKey}}

{
    "messages": [
        {
            "role": "user",
            "content": "Resuelve Fibonacci en javascript"
        }
    ]
}